### ISSUE TITLE
Add variant headwords for anusvāra and vargapañcamas

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-kannada#12]
Currently ಅಗ್ನಿಪಂಚೀಕರಣ only shows up if agnipaMchiikaraNa is searched for. No hits if agnipanchiikaraNa is searched for. Will be nice (across all dicts) to have both variants in headwords.

**Comment by vvasuki** [comment]
Try agnipanciikarana
According to the convention used, ch stands for छ

**Comment by vvasuki** [comment]
Actually, rechecking - this is unintended. Ought to be using ch vs Ch.

**Comment by vvasuki** [comment]
fixed for this repo
