### ISSUE TITLE
Alar Kannada-Eng Dict

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-kannada#3]
150,000+ entries
Online interface:
https://alar.ink
Data is here:
https://github.com/alar-dict/data

**Comment by vvasuki** [comment]
Wonderful! Transformed and created the babyon file. Stardict files should be available shortly. 

BTW, @suhasm - Not widely announced yet (for a reason), but wonderful sa-kn dict shabdArtha-kaustubha is available as well.

## Thanks to shrI @knadh 
Thanks to shrI @knadh for his service to kannaDa culture and its votaries. (For context, we are a bunch of language lovers who love to use heavily dicts in the popular stardict format and hence serve ourselves by transforming and publishing dicts that way - see https://github.com/indic-dict and https://sanskrit-coders.github.io/dictionaries/offline/ ). 

I had met the author V. Krishna in a shAkuntala study group meeting a couple of years ago and had (apparently unsuccessfully) tried to briefly explain the tech and get him to send me the data - but had not followed up and he did not seem convinced. Very very glad that you succeeded and open sourced the data!

**Comment by knadh** [comment]
Thanks @vvasuki. Great to see the data proliferating already :)
