### ISSUE TITLE
Request: add ಮೈಸೂರು ವಿಶ್ವವಿದ್ಯಾನಿಲಯ ವಿಶ್ವಕೋಶ (Wikisource)

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-kannada#7]
https://kn.wikisource.org/wiki/%E0%B2%B5%E0%B2%B0%E0%B3%8D%E0%B2%97:%E0%B2%AE%E0%B3%88%E0%B2%B8%E0%B3%82%E0%B2%B0%E0%B3%81_%E0%B2%B5%E0%B2%BF%E0%B2%B6%E0%B3%8D%E0%B2%B5%E0%B2%B5%E0%B2%BF%E0%B2%A6%E0%B3%8D%E0%B2%AF%E0%B2%BE%E0%B2%A8%E0%B2%BF%E0%B2%B2%E0%B2%AF_%E0%B2%B5%E0%B2%BF%E0%B2%B6%E0%B3%8D%E0%B2%B5%E0%B2%95%E0%B3%8B%E0%B2%B6

**Comment by vvasuki** [comment]
सिद्धम्।
